:sparkles: Add Shop configuration endpoints
MyParcelCOM/marketplace-skeleton pull request #50
Opened 2024-09-23 15:51 UTC by yoerriwalstra

**Changes**
- add `GET /shops/{shopId}/configuration-schema` endpoint
- add `POST /shops/{shopId}/configure` endpoint
- add `configurations` table migration

**Related issue**
https://myparcelcombv.atlassian.net/browse/MP-6823

2024-09-23 16:06 UTC, yoan-myparcel commented on database/migrations/2024_09_23_154703_create_account_configurations_table.php
> +};
What would be the purpose of this table? If it is to keep the values of a configuration form submission, that could be saved directly in the `shops` table, which is individual per marketplace. I suggest we do not mention where the configuration is saved as it might differ from case to case.

2024-09-23 16:13 UTC, yoan-myparcel commented on app/Shops/Http/Controllers/ShopController.php
> +        $form = new Form(/* Field instances go here */);
Lets expand further and construct a simple form with fields like a checkbox, a text field. Some samples that come to my mind:
- text - _Order number prefix_
- select - _Default shop currency_
- checkbox - _Exclude orders imported from Amazon_

That way we show how the form is constructed. Similarly we did for the other endpoints. For example, the get order endpoint has an order with example data fully set.

2024-09-24 07:31 UTC, yoerriwalstra commented on database/migrations/2024_09_23_154703_create_account_configurations_table.php
> +};
I was pretty much guessing here, but yeah, having the config values on the `shops` table should work fine

2024-09-26 08:14 UTC, yoan-myparcel requested changes

2024-09-26 08:14 UTC, yoan-myparcel commented on app/Shops/Http/Controllers/ShopController.php
> +        return new ConfigurationResponse($form);
This needs updating because the commons package Field classes now use `label` instead of `description`. Furthermore, for the example's sake lets shorten the text in the label and make them always start with a capital letter.

2024-09-26 11:47 UTC, yoerriwalstra commented on app/Shops/Http/Controllers/ShopController.php
> +        return new ConfigurationResponse($form);
will update after latest [`marketplace-commons` PR](https://github.com/MyParcelCOM/marketplace-commons/pull/41) is released

2024-09-26 14:28 UTC, yoan-myparcel approved these changes

2024-09-26 14:28 UTC, merged